### ISSUE TITLE
Wishlist: "END" statement functionality

### ISSUE THREAD

**Issue by connoralbright** [onerobotics/tp_plus#9]
The "END" statement does not seem to be implemented. At least I can not find a test case. 
Which is amusing considering: http://www.onerobotics.com/posts/2016/embrace-the-end-statement/

Really, really nice library. Thank you.

**Comment by unreal** [comment]
Haha, you're right. I didn't use END much 2 years ago ;) Happy to accept a pull request!

**Comment by connoralbright** [comment]
I thought I was going crazy when I found it was not supported! 

For anyone reading this that has the same problem: I've been using
` eval "end"`
It seems to be working well. 

I'll see what I can do about a pull request, but I'm not optimistic. I have had a very hard figuring out how the library actually works, it's not anything like what I am used to. (With that said, I just took another peek, and it might be as single as copying the "`ABORT`" code.

**Comment by unreal** [comment]
I think there will likely be parser issues if you attempt to add an end-statement (since it's already used to close if-statements, for-loops, etc.).

It would probably be easier to add "end" functionality with a return-statement.

Here's how I would do it:
1. Add a test to test_scanner.rb to make sure the scanner can scan "return" and return a RETURN token
2. Add code to scanner.rb to get test to pass
3. Add a test to test_parser.rb to scan "return" and return a ReturnNode (or maybe a SimpleStatementNode that could consolidate things like ABORT, PAUSE, etc.)
4. Add code to generators/parser.y to accept the RETURN token and correctly return the node
5. Add a test to test_interpreter to scan "return" and return the program "END ;"
6. Add code to the appropriate node to get it to evaluate correctly

GitHub has tutorials on creating pull requests.

Easier said than done if Ruby is not familiar to you, but it's probably worth learning. (Although I admit a lot of the code in this library is pretty gross and could use a good overhaul.)
